### PR TITLE
qlearn f1 followlane

### PR DESCRIPTION
**Pull request by pjfernandecabo**
Agent **F1** following **right Lane** with **Qlearn** algorithm.

### CODE REVIEW

**Comment by rubenlucas93** [comment]
image

**Comment by pjfernandecabo** [comment]
Are you sure you are launching with thos sentence?: 
python main_rlstudio.py -n qlearn -a f1 -e simple -f config/config_f1followlane_qlearn.yaml

In your error, you are trying to launch **DQN** algorithm when the correct is training with **QLEARN**
Pls try again and tell me

**Comment by sergiopaniego** [comment]
* We should update naming in `f1_env_camera`. 
The first class (F1CameraEnv) is currently only used for Q-learning Follow line environment and the second one (QlearnF1FollowLaneEnvGazebo) is only used for Q-learning Follow lane. They should follow a common naming convention. We can rename the first one to something similar (what's your opinion @pjfernandecabo?). Is the code duplicated? 

* I think that the naming of environments along the whole project needs a review. We could open a new issue to explore this task. The project could follow a MVC architecture, so it's easier to maintain and reuse code. 

What do you think @pjfernandecabo?

**Comment by sergiopaniego** [comment]
I have updated the naming so it follows the same convention in `f1_env_camera`.
I have also:
* Removed unused config files. I think there is still a lot to improve in the config files. They have too much information regarding other envs/algos that I don't know if it's really needed. 
* I have removed functions that are not used. We should not copy/paste code since I have detected a lot of duplicated code and unused.

I think we need to still add already trained models for both Q-learning follow line and follow lane and link them on the config files so you can directly used inference mode. That would be the last task before merging. What do you think @pjfernandecabo ?

- [ ] Generate and upload Q-learning models for both follow line and follow lane. Link them on the config files.

**Comment by sergiopaniego** [comment]
Update:

I have generated example inference files for both follow line and follow lane problems. I have also added the generated files to the checkpoint folder. 

I have some questions regarding this topic @pjfernandecabo:

* For each problem, the saving procedure is different. `save_model_qlearn` is used for follow lane and `save_model` for follow line. The should be calling the same procedure, since they are trying to save the same algorithm structure? They end up saving files in different locations (folders).
* The saving pipelines generate files that are not directly linked for inference in the config file. Are they needed? I'm talking about `_STATES_COUNTER`,  `STATES_CUM_REWARD.pkl` and `STATES_STEPS.pkl `. Why are they generated?
* The saving procedure for follow lane doesn't generate an `actions_set_` file. Even though it's not generated, linking to the follow line `actions_set_` file it works correctly. Is this file needed?

Thanks!

**Comment by sergiopaniego** [comment]
I can see a few calls to `plot_steps_vs_epoch` in the Q-learning training pipeline for the follow-line problem but this function is not found in any file in the project. Is there some file missing?

**Comment by pjfernandecabo** [comment]
> 
Totally agree. The first version of RL-Studio was designed for a single simulator and a single agent with a single task, which was to follow the line. Now we have advanced and we have in RL-Studio multiple agents, different simulators, and multitasking, and we must adapt it. A few weeks ago, we had agreed to use names of the form:
algorithm_agent_task_simulator because in this way it meets the tool objectives.
For example:
DDPG_car_FollowLane_Carla.

Therefore, regarding your first question, F1CameraEnv could be called QlearnF1FollowLineEnvGazebo

Regarding the second question, I agree, especially considering incorporating the Carla simulator. So, maybe we have to explore this second issue before solve the first one.

**Comment by pjfernandecabo** [comment]
> * We should update naming in `f1_env_camera`.
>   The first class (F1CameraEnv) is currently only used for Q-learning Follow line environment and the second one (QlearnF1FollowLaneEnvGazebo) is only used for Q-learning Follow lane. They should follow a common naming convention. We can rename the first one to something similar (what's your opinion @pjfernandecabo?). Is the code duplicated?
> * I think that the naming of environments along the whole project needs a review. We could open a new issue to explore this task. The project could follow a MVC architecture, so it's easier to maintain and reuse code.
> 
> What do you think @pjfernandecabo?

Totally agree. The first version of RL-Studio was designed for a single simulator and a single agent with a single task, which was to follow the line. Now we have advanced and we have in RL-Studio multiple agents, different simulators, and multitasking, and we must adapt it. A few weeks ago, we had agreed to use names of the form:
algorithm_agent_task_simulator because in this way it meets the tool objectives.
For example:
DDPG_car_FollowLane_Carla.

Therefore, regarding your first question, F1CameraEnv could be called QlearnF1FollowLineEnvGazebo

Regarding the second question, I agree, especially considering incorporating the Carla simulator. So, maybe we have to explore this second issue before solving the first one.

**Comment by pjfernandecabo** [comment]
> I can see a few calls to `plot_steps_vs_epoch` in the Q-learning training pipeline for the follow-line problem but this function is not found in any file in the project. Is there some file missing?

Class F1Trainer, line 229:
I have never used it, it appeared in the first version when there was only the qlearn algorithm. In the next code refactorized, we have to delete all old references.

**Comment by pjfernandecabo** [comment]
> Update:
> 
> I have generated example inference files for both follow line and follow lane problems. I have also added the generated files to the checkpoint folder.
> 
> I have some questions regarding this topic @pjfernandecabo:
> 
> * For each problem, the saving procedure is different. `save_model_qlearn` is used for follow lane and `save_model` for follow line. The should be calling the same procedure, since they are trying to save the same algorithm structure? They end up saving files in different locations (folders).
> * The saving pipelines generate files that are not directly linked for inference in the config file. Are they needed? I'm talking about `_STATES_COUNTER`,  `STATES_CUM_REWARD.pkl` and `STATES_STEPS.pkl `. Why are they generated?
> * The saving procedure for follow lane doesn't generate an `actions_set_` file. Even though it's not generated, linking to the follow line `actions_set_` file it works correctly. Is this file needed?
> 
> Thanks!

save_model and save_model_qlearn should be unified in only one variable. Like a directory where to save models: Now I save them in "logs" folder, but cartpole task saves in "checkpoints" I think.

Regarding pkl files, all of them come from the first version, but I think only those ended in _QTABLE are necessary for inference. Let's check them.

**Comment by pjfernandecabo** [comment]
fixed in the new version V1.2

**Pull request closed without merging**
