### PR TITLE
issue 74 dqn f1 multitask

### PR DESCRIPTION
**Pull request by pjfernandecabo**
Fixed issues
dqn_keras: in class DQNF1FollowLine, method get_qs()

Added multitasking for F1. Before F1 agent only could work in Follow Line task. Now F1 can work with both, Follow line and Follow lane.

Delete requirements.txt from this issue

### CODE REVIEW

**Comment by rubenlucas93** [comment]
image
Then
image
And then 
image

**Comment by rubenlucas93** [comment]
Fixed. Problems of gym libraries:

Now get two errors. One is.
image


And when I solve this adding the commited modification:
image

**Comment by pjfernandecabo** [comment]
Have you modified config_"file".yaml?. Last problem is about neural nets and its configuration.

**Comment by pjfernandecabo** [comment]
Fixed neural net problem in the second commit. Effectively, there was an error where I tried to pass an image 480x640 size into NN when the latter was 32x32 size. Problem solved.

Captura de Pantalla 2022-09-21 a la(s) 08 34 17

**Review by rubenlucas93 — APPROVED** [review]

**Pull request merged**
