### PR TITLE
first commit with f1 dqn fixes

### PR DESCRIPTION
**Pull request by rubenlucas93**
DONT MERGE THIS BRANCH UNTIL WE BOTH APROVE IT!!!

DQN F1 is not working in the main branch.
First because of my regressions and then because it looks like there are missing commits.

Once it is working for all of us let's merge it

### CODE REVIEW

**Comment by rubenlucas93** [comment]
Beside the following error. I miss the libraries. (in the cartpole I did not update it neither) so we have to figure it out how to make the installation of libraries simple and consistent with the problems we are reproducing. Basically the F1 and the cartpole.

**Comment by rubenlucas93** [comment]
Missing also fix paths of imports in f1 ddpg
imagen

Those must be set from rl_studio root directory

**Comment by pjfernandecabo** [comment]
> Missing also fix paths of imports in f1 ddpg imagen
> 
> Those must be set from rl_studio root directory

this seems to refer to install libraries in your local environment

**Comment by pjfernandecabo** [comment]
> Beside the following error. I miss the libraries. (in the cartpole I did not update it neither) so we have to figure it out how to make the installation of libraries simple and consistent with the problems we are reproducing. Basically the F1 and the cartpole. image

I think we have to update requeriments.txt

**Comment by pjfernandecabo** [comment]
> Beside the following error. I miss the libraries. (in the cartpole I did not update it neither) so we have to figure it out how to make the installation of libraries simple and consistent with the problems we are reproducing. Basically the F1 and the cartpole. image

I've found this error, and it comes from config.yaml. We are trying to feed in neural nets, an image too big.

**Comment by pjfernandecabo** [comment]
closed Pull Request. It has been fixed in PR "issue-74_dqn_f1_multitask"

**Pull request closed without merging**
